### ISSUE TITLE
Choose the placement of Alan activation button in UI

### ISSUE THREAD

**Issue by sambhavsaxena** [alan-ai/alan-sdk-android#4]
It some times is placed on the bottom-left corner, and on the bottom-right corner some other time, in a minimalistic application I created using Android Studio, and migrating the code to Kotlin, but I don't think there's an issue with the migration.

**Comment by snyuryev** [comment]
@sambhavsaxena 
Could you provide some details about your app? Do you use any of our tutorials?

**Comment by sambhavsaxena** [comment]
> @sambhavsaxena 
> Could you provide some details about your app? Do you use any of our tutorials? 


it's just a basic one page application that implements Alan using a secret key and a method defined in one of the Alan's documentations [found here](https://alan.app/docs/client-api/android/android-api)

**Comment by snyuryev** [comment]
Once you put AlanButton inside your xml layout - position is set to right by default. 
```app:button_horizontal_align="right"```

Please follow the instructions from "Integrations" section inside of your project in Alan Studio (https://studio.alan.app)
