### ISSUE TITLE
Failed to resolve: com.budiyev.android:code-scanner:2.1.0

### ISSUE THREAD

**Issue by JanStaelens** [alan-ai/alan-sdk-android#5]
## Bug Report:
In Android Studio, when trying to import app:alan:sdk in a project and building with it
You'll get:
Failed to resolve: com.budiyev.android:code-scanner:2.1.0

After some research
This used to be on JCenter which has become deprecated.

They indicated (https://github.com/yuriy-budiyev/code-scanner/issues/120) they've moved to  'https://jitpack.io'. But when I add that as a dependencyresolution setting in Android Studio I still get errors.

settings.gradle:
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

I've tested 
implementation 'app.alan:sdk:4.12.0' and implementation 'app.alan:sdk:4.18.0'

**Comment by snyuryev** [comment]
@JanStaelens please add jcenter() to the repositories list
https://alan.app/docs/client-api/android/android-api/#troubleshooting

**Comment by JanStaelens** [comment]
Thanks, that did the trick. I thought JCenter was no longer working since february so for some reason I kept trying different things. I'll play around a bit more now.
I'm trying to execute an http call to a local server from my android app when Alan recognises specific commands. I'll go through documentations and see if I can figure out if I can get Alan to send back specific events and string parameters back to the android device.

**Comment by snyuryev** [comment]
You can send a command from the Alan Studio script to your Android app. Inside you app handle this command and do http call (or any stuff you want):
https://alan.app/docs/server-api/commands-and-responses/#sending-commands-to-the-app

PS: closing this issue as resolved. If you need additional help please open separated issue.
