### ISSUE TITLE
Could not find com.budiyev.android:code-scanner:2.1.0

### ISSUE THREAD

**Issue by emmanuelo7** [alan-ai/alan-sdk-android#6]
hello there , i watched your video ( Building a Voice Assistant for an Android App
 )
I did exactly what you said to do in your video but an error message appears
:Could not find com.budiyev.android:code-scanner:2.1.0.
Required by:
    project :app > app.alan:sdk:4.12.0

**Comment by snyuryev** [comment]
@emmanuelo7 good to know!
